version: '3'
services:
  api:
    build: ./api
    container_name: app-api
    command: npm run start
    restart: unless-stopped
    environment:
      - PORT=3001
      - MONGO_URL=mongodb+srv://krutakova:PSyFbaVLR4NUdecG@cluster0.qmq9e.mongodb.net/bestrunner?retryWrites=true&w=majority
      - AUTH_API_URL=http://auth:3001/api
    depends_on:
      - api_db
    networks:
      - app-network

  api_db:
    image: mongo:latest
    container_name: app-api_db
    volumes:
      - mongodb_api:/data/db
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    container_name: app-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - app-network

volumes:
  mongodb_api:

networks:
  app-network:
    driver: bridge